# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20161128_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': '\u041e\u0442\u0432\u0435\u0442', 'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441', 'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b'},
        ),
    ]
