# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_auto_20161130_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=512, unique=True)),
                ('expires', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.User')),
            ],
            options={
                'verbose_name': '\u0421\u0435\u0441\u0441\u0438\u044f',
                'verbose_name_plural': '\u0421\u0435\u0441\u0441\u0438\u0438',
            },
        ),
    ]
